# Generated by Django 2.2.1 on 2019-12-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.UUIDField()),
                ('arrival_time', models.DateTimeField(max_length=500)),
                ('departure_time', models.DateTimeField(max_length=500)),
                ('navigation_section', models.CharField(max_length=100)),
                ('operating_time', models.CharField(max_length=100)),
                ('airplane_type', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'air_schedules',
                'ordering': ('created',),
            },
        ),
    ]
